apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests
configMapGenerator:
- name: nsx-node-agent-restarter-script
  namespace: nsx-system-restarter
  files:
  - restart-nsx-node-agents.sh
- name: nsx-node-agent-restarter-env
  namespace: nsx-system-restarter
  envs:
  - config/restart-nsx-node-agents.env
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated-by-kustomization
patches:
- path: config/cronjob-parameters.yaml
  target:
    group: batch
    version: v1
    kind: CronJob
    name: nsx-node-agent-restarter-cj