apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests
configMapGenerator:
- name: nodes-purge-script
  namespace: nsx-system-purger
  files:
  - nodes-purge.sh
- name: nodes-purge-env
  namespace: nsx-system-purger
  envs:
  - config/nodes-purge.env
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated-by-kustomization
patches:
- path: config/cronjob-parameters.yaml
  target:
    group: batch
    version: v1
    kind: CronJob
    name: nodes-purge-cj