kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nsx-node-agent-restarter-crb
subjects:
  - kind: ServiceAccount
    name: nsx-node-agent-restarter-sa
    namespace: nsx-node-agent-restarter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nsx-node-agent-restarter-cr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: nsx-node-agent-restarter-sa
  namespace: nsx-node-agent-restarter
