apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodes-purge-cr 
rules:
- apiGroups: [""]
  resources:
    - "pods"
    - "pods/log"
    - "namespaces"
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources:
    - "nodes"
  verbs: ["get", "list", "watch"]
- apiGroups: ["security.openshift.io"]
  resources:
    - "securitycontextconstraints"
  resourceNames:
    - "privileged"
  verbs: ["use"]
