apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nsx-node-agent-restarter-cr 
rules:
- apiGroups: [""]
  resources:
     - "pods"
     - "pods/log"
  verbs: ["get", "list", "create", "delete", "watch"]
