kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nsx-node-agent-restarter-rb
  namespace: nsx-system
subjects:
  - kind: ServiceAccount
    name: nsx-node-agent-restarter-sa
    namespace: nsx-system-restarter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nsx-node-agent-restarter-cr